### ISSUE TITLE
[webusb] Using a click handler, still getting a DOMException 

### ISSUE THREAD

**Issue by edouardswiac** [LedgerHQ/ledgerjs#315] opened 2019-03-05 22:10 UTC
I am well aware of "Important: The transport functions create() and listen() must be in the context of an user interaction (like a "click" event), otherwise it will fails with DOM Exception." but I can't make it work. I am using a vue app and my transport code is in a click handler.

```
<script>
[...]
methods:    
  enrollLedger() {
      TransportWebUSB.create().then(transport => {
          console.log("T", transport); // this works
          const btc = new Btc(transport);
          console.log(btc); // this works
          btc.getWalletPublicKey("44'/0'/0'/0").then(o => console.log(o)); // nope

      })
        .catch(err => console.error(err));
    },
[snip]
<template>
 <v-btn @click="enrollLedger">Ledger</v-btn>
</template>
```
Could it be vue?

**Comment by edouardswiac** [comment] 2019-03-05 22:57
If I don't open the BTC app I get a Transport error 
```Ledger device: Security not satisfied (dongle locked or have invalid access rights) (0x6982)```

**Comment by edouardswiac** [comment] 2019-03-05 23:58
U2F transport is working for me BTW

**Comment by Chappell-C** [comment] 2019-03-06 08:36
@gre Hi,I am experiencing the same problem.What is the cause of this problem?

**Comment by Chappell-C** [comment] 2019-03-06 09:19
@edouardswiac If you find a solution, Please let me know.Thank you

**Comment by gre** [comment] 2019-03-06 19:32
I can reproduce the problem. investigating..

**Comment by gre** [comment] 2019-03-06 19:38
ok so it seems the latest BTC app don't have `webusb` enabled. we'll fix that.

in the meanwhile i'll also improve the error returned by the transport!

**Comment by patwhite** [comment] 2019-03-07 17:19
@gre What's the time frame for a fix to this to be generally available?

**Comment by gre** [comment] 2019-03-07 17:34
it will be in next BTC app release, not sure exactly when it will be pushed.

**Comment by patwhite** [comment] 2019-03-07 17:57
So, right now, I literally can't integrate with the legder in any way. I'm getting a weird error message when I try to use the old Bitcoin App / Ledger Manager, the web usb is broken here, and the U2F is broken because of chrome. Do you have any suggestions? I posted some info to the ledger-developers slack about my issues with the ledger-manager and am chatting with Jean. But, as of right now, all web based integrations with ledger are broken.

Re: timeframe, is it like, a day or two, or more like a month?

**Comment by timothywangdev** [comment] 2019-03-13 19:49
Same here. We are wallet developers . Both U2F and webusb are broken, which is causing lots of troubles.

**Comment by monokh** [comment] 2019-03-14 16:13
Ditto on the above. To give a bit more concise description.

BTC app does not work under:

- Latest ledgerjs lib versions
- Chrome v73
- either WebUSB or U2F

Chrome v73 is under stable tag now: https://www.chromestatus.com/features/schedule
Pretty soon, a huge number of users will move onto it and the BTC ledger communication will stop working.

**Comment by edouardswiac** [comment] 2019-05-31 00:26
@gre has the next BTC app been released? Thanks!

**Comment by gre** [comment] 2019-06-01 16:08
@edouardswiac yes I think so. seems to work for me.

**Closed** 2019-06-03 21:42 UTC
